### PR TITLE
Added -x flag to ignore unresolved import errors

### PR DESCRIPTION
**Pull request by adriamb**
It's usefull when trying to analize a big project that contains external dependencies, and we need to trim down the graph a litte to understand it better.

### CODE REVIEW

**Comment by kisielk** [comment]
Now that I think about it, perhaps it would be a good idea to display the unresolved imports in the graph? Could be a red node for example. It would take a bit more work than this PR but I think the result would be better than just bailing or not displaying them at all

**Comment by amassanet** [comment]
Of course is a good idea, but it depends on what do you want to do. In order to start understanding the module structure for a medium project, the main thing is to reduce complexity ; adding more nodes does not help (at least for me). So -x might mean "hide non-project-packages" (that this is not really true at this moment because if previously installed they will appear). It could be improved in this way, also.

**Comment by kisielk** [comment]
Right. I guess I don't really understand how you intend this to work? Most of the time when you check out a project or download it with `go get` you will also have the dependancies. So is your idea to intentionally leave them out?

**Comment by amassanet** [comment]
Yes, It is a "ok, let's me see what's in this project without caring about external dependencies" quick & dirty flag.

**Comment by amassanet** [comment]
Nice. Why not, it does the work for (both) clean and codebases with unresolved or broken dependencies.

**Comment by kisielk** [comment]
Okay, are you interested in doing up a PR for that? I think the best way would be to make `ignored` a set of regular expressions and then add an appropriate expression there.

**Comment by amassanet** [comment]
Ok.

If I use the `ignored` with regexp it means that I should use negative regexps to add a package?

Negative regexps are quite weird thing (http://stackoverflow.com/questions/406230/regular-expression-to-match-line-that-doesnt-contain-a-word), so it maybe ´ignored´ should be an array of

```go
type IgnoredMatch struct {
     regexp string
     negate bool
}
```
then use a `negate` to negate the `regexp` match.

So, it does not have more sense to create just a list of package name regexp matchings in order to remove the "double negation" (negate the ignored)? 

so, that's just:

```go
type PackageMatch struct {
     regexp string
     negate bool
}
```

**Comment by kisielk** [comment]
hm, this needs some though I guess. All the current options remove packages with an exclusion filter, what we're trying to add is an inclusion filter..

**Pull request closed without merging**
